import { useCallback, useEffect, useState } from "react";
import AdminPageState from "../../components/admin/AdminPageState";
import { getAnalyticsOverview, getOrdersByHour, getPopularItems, getRevenue } from "../../services/analyticsService";
import { getCanteens } from "../../services/canteenService";

const iso = (date) => date.toISOString().slice(0, 10);
const ranges = { today: 0, "7d": 6, "30d": 29 };

export default function AdminAnalytics() {
  const [range, setRange] = useState("7d"); const [canteenId, setCanteenId] = useState(""); const [canteens, setCanteens] = useState([]); const [customFrom, setCustomFrom] = useState(""); const [customTo, setCustomTo] = useState(""); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => {
    setLoading(true); setError("");
    try { const to = new Date(); const from = new Date(); from.setDate(from.getDate() - ranges[range]); const params = range === "custom" ? { from: customFrom, to: customTo } : { from: iso(from), to: iso(to) }; if (canteenId) params.canteenId = canteenId; const [overview, hours, revenue, items] = await Promise.all([getAnalyticsOverview(params), getOrdersByHour(params), getRevenue(params), getPopularItems(params)]); setData({ overview: overview.data.data, hours: hours.data.data.hours, revenue: revenue.data.data.revenue, items: items.data.data.items }); }
    catch (requestError) { setError(requestError.message); } finally { setLoading(false); }
  }, [range, canteenId, customFrom, customTo]);
  useEffect(() => { getCanteens().then((response) => setCanteens(response.data.data?.canteens || [])).catch(() => {}); }, []);
  useEffect(() => { if (range !== "custom" || (customFrom && customTo)) load(); }, [load, range, customFrom, customTo]);
  const maxOrders = Math.max(1, ...(data?.hours || []).map((row) => row.orders));
  const maxRevenue = Math.max(1, ...(data?.revenue || []).map((row) => row.revenue));
  return <div><div className="admin-page-heading"><div><p className="admin-kicker">Performance intelligence</p><h2 className="admin-title">Analytics</h2><p className="admin-subtitle">Understand demand, revenue and preparation performance.</p></div><div className="flex flex-wrap gap-2"><select aria-label="Filter by canteen" value={canteenId} onChange={(e) => setCanteenId(e.target.value)} className="field mt-0 w-auto"><option value="">All canteens</option>{canteens.map((canteen) => <option key={canteen.id} value={canteen.id}>{canteen.name}</option>)}</select><select aria-label="Filter by date range" value={range} onChange={(e) => setRange(e.target.value)} className="field mt-0 w-auto"><option value="today">Today</option><option value="7d">Last 7 Days</option><option value="30d">Last 30 Days</option><option value="custom">Custom range</option></select>{range === "custom" && <><input aria-label="From date" type="date" value={customFrom} onChange={(e) => setCustomFrom(e.target.value)} className="field mt-0 w-auto" /><input aria-label="To date" type="date" value={customTo} onChange={(e) => setCustomTo(e.target.value)} className="field mt-0 w-auto" /></>}</div></div><AdminPageState loading={loading} error={error} onRetry={load}>{data && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Total Orders", data.overview.totalOrders], ["Revenue", `Rs. ${data.overview.revenue}`], ["Avg Preparation", `${data.overview.averagePreparationTime} min`], ["Avg Orders/Hour", data.overview.averageOrdersPerHour]].map(([label, value]) => <div key={label} className="kpi-card"><p className="kpi-label">{label}</p><p className="kpi-value">{value}</p></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Chart title="Orders by hour" rows={data.hours} labelKey="hour" valueKey="orders" max={maxOrders} /><Chart title="Revenue by day" rows={data.revenue} labelKey="date" valueKey="revenue" max={maxRevenue} currency /><Chart title="Popular items" rows={data.items} labelKey="name" valueKey="quantitySold" max={Math.max(1, ...(data.items || []).map((row) => row.quantitySold))} /><div className="admin-panel"><p className="admin-kicker">Demand signals</p><h3 className="panel-title">Peak hours</h3><div className="mt-4 space-y-3">{(data.overview.peakHours || []).map((row) => <div key={row.hour} className="flex justify-between rounded-xl bg-slate-50 px-3 py-3 text-sm"><span className="font-bold text-slate-700">{row.hour}</span><span className="font-black text-cyan-700">{row.orders} orders</span></div>)}{!data.overview.peakHours?.length && <p className="text-sm text-slate-500">No peak-hour data for this period.</p>}</div></div></div></>}</AdminPageState></div>;
}

function Chart({ title, rows, labelKey, valueKey, max, currency = false }) {
  return <div className="admin-panel"><p className="admin-kicker">Report</p><h3 className="panel-title">{title}</h3><div className="mt-5 max-h-80 space-y-3 overflow-y-auto">{rows.map((row) => <div key={row[labelKey]} className="grid grid-cols-[minmax(70px,1fr)_3fr_auto] items-center gap-3 text-xs"><span className="truncate font-semibold text-slate-500">{row[labelKey]}</span><span className="h-3 overflow-hidden rounded-full bg-slate-100"><span className="block h-full rounded-full bg-cyan-500" style={{ width: `${Math.max(2, (row[valueKey] / max) * 100)}%` }} /></span><b className="text-slate-800">{currency ? `Rs. ${row[valueKey]}` : row[valueKey]}</b></div>)}</div></div>;
}
