import { useCallback, useEffect, useState } from "react";
import { Archive, Edit3, Plus, Power, Utensils } from "lucide-react";
import { archiveMenuItem, createMenuItem, getMenuForManagement, updateMenuAvailability, updateMenuItem } from "../../services/adminService";
import AdminPageState from "../../components/admin/AdminPageState";
import MenuForm from "../../components/admin/MenuForm";
import { getCanteens } from "../../services/canteenService";

export default function MenuManagement() {
  const [items, setItems] = useState([]); const [canteens, setCanteens] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState(null); const [showForm, setShowForm] = useState(false); const [submitting, setSubmitting] = useState(false); const [busy, setBusy] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const [menuResponse, canteenResponse] = await Promise.all([getMenuForManagement({ limit: 100 }), getCanteens()]); setItems(menuResponse.data.data?.items || []); setCanteens(canteenResponse.data.data?.canteens || []); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const save = async (payload) => { setSubmitting(true); setError(""); try { const response = editing ? await updateMenuItem(editing._id, payload) : await createMenuItem(payload); const item = response.data.data; setItems((current) => editing ? current.map((entry) => entry._id === item._id ? item : entry) : [item, ...current]); setEditing(null); setShowForm(false); } catch (requestError) { setError(requestError.message); } finally { setSubmitting(false); } };
  const toggle = async (item) => { setBusy(item._id); try { const response = await updateMenuAvailability(item._id, !item.isAvailable); const updated = response.data.data; setItems((current) => current.map((entry) => entry._id === updated._id ? updated : entry)); } catch (requestError) { setError(requestError.message); } finally { setBusy(""); } };
  const archive = async (item) => { if (!window.confirm("Archive this menu item?")) return; setBusy(item._id); try { const response = await archiveMenuItem(item._id); const updated = response.data.data; setItems((current) => current.map((entry) => entry._id === updated._id ? updated : entry)); } catch (requestError) { setError(requestError.message); } finally { setBusy(""); } };
  const canteenName = (item) => canteens.find((canteen) => (canteen.id || canteen._id) === (item.canteen?._id || item.canteen))?.name || "Canteen not assigned";
  return <div><div className="admin-page-heading"><div><p className="admin-kicker">Catalog operations</p><h2 className="admin-title">Menu management</h2><p className="admin-subtitle">Keep every item, price and availability state accurate for customers.</p></div><button onClick={() => { setEditing(null); setShowForm(true); }} className="button-primary"><Plus size={17} /> Add menu item</button></div>{(showForm || editing) && <div className="admin-panel mb-6"><div className="mb-5 flex items-start justify-between gap-3"><div><p className="admin-kicker">Menu item editor</p><h3 className="panel-title">{editing ? "Edit menu item" : "Create menu item"}</h3></div><Utensils className="text-cyan-600" size={22} /></div><MenuForm item={editing} canteens={canteens} onSubmit={save} onCancel={() => { setShowForm(false); setEditing(null); }} submitting={submitting} /></div>}<AdminPageState loading={loading} error={error} empty={!items.length} onRetry={load}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item._id} className="admin-panel overflow-hidden p-0"><div className="h-36 bg-slate-100">{item.imageUrl ? <img src={item.imageUrl} alt="" className="h-full w-full object-cover" onError={(event) => { event.currentTarget.style.display = "none"; }} /> : <div className="flex h-full items-center justify-center text-slate-300"><Utensils size={34} /></div>}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-slate-950">{item.name}</h3><p className="mt-1 text-xs font-semibold text-slate-500">{canteenName(item)} · {item.category}</p></div><span className={`status-badge ${item.isAvailable ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-500"}`}>{item.isAvailable ? "Available" : "Sold out"}</span></div><p className="mt-3 line-clamp-2 min-h-10 text-sm text-slate-500">{item.description || "No description provided."}</p><div className="mt-4 flex items-end justify-between"><p className="text-xl font-black text-slate-950">Rs. {item.price}</p><p className="text-xs font-bold text-slate-400">{item.preparationTime} min prep</p></div><div className="mt-5 flex flex-wrap gap-2 border-t border-slate-100 pt-4"><button disabled={busy === item._id} onClick={() => toggle(item)} className="button-secondary text-xs"><Power size={14} /> {item.isAvailable ? "Mark sold out" : "Make available"}</button><button onClick={() => { setEditing(item); setShowForm(false); }} className="button-secondary text-xs"><Edit3 size={14} /> Edit</button><button disabled={busy === item._id} onClick={() => archive(item)} className="button-secondary text-xs text-red-600 hover:border-red-200 hover:bg-red-50"><Archive size={14} /> Archive</button></div></div></article>)}</div></AdminPageState></div>;
}
